version: 0.2
env:
  parameter-store:
    AWS_ACCOUNT_ID: "/qppar-sf/account_id"
    AUTH_URL: "/qppar-sf/${ENVIRONMENT}/conversion_tool/QPPA_TOKEN_URL"
    FMS_URL: "/qppar-sf/${ENVIRONMENT}/conversion_tool/FMS_URL"
    FMS_TOKEN: "/qppar-sf/${ENVIRONMENT}/conversion_tool/FMS_TOKEN"
    FMS_PATH: "/qppar-sf/${ENVIRONMENT}/conversion_tool/FMS_PATH"
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - chmod +x ./qppsfct-copy-certs.sh
      - ./qppsfct-copy-certs.sh $ENVIRONMENT $AWS_DEFAULT_REGION
      - chmod +x ./upload-part-file.sh
      - ./upload-part-file.sh $AUTH_URL $FMS_URL $FMS_TOKEN $FMS_PATH