name: "Detect hardcoded secrets"

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push: 

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
