name: Update Participation File

on:
  push:
    branches:
      - feature/QPPSF-10875_Update-Participation-File
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Check PII & Credentiail leaks
        uses: zricethezav/gitleaks-action@6e41781c235feb424ecc3435610dce20ad349a70 # pin@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/qppsf-dev-githubactions-conversiontool-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Retrieve Dev Unformatted File
          if: github.ref == 'refs/heads/feature/QPPSF-10875_Update-Participation-File'
          run: |
            ${{ format('aws s3 cp s3://{0}/{1} .', secrets.DEV_S3_BUCKET, secrets.DEV_PART_FILE) }}

      - name: Run python formatting for Dev
        uses: actions/setup-python@v4
        if: github.ref == 'refs/heads/feature/QPPSF-10875_Update-Participation-File'
        with:
          python-version: '3.10'
          run: |
            pip install openpyxl simplejson collections
            python ~/tools/scripts/format-participation-file.py ${{ secrets.DEV_PART_FILE }} testingCpcPlusValidationFile.json

      - name: Upload file to Dev s3
          if: github.ref == 'refs/heads/feature/QPPSF-10875_Update-Participation-File'
          run: |
            ${{ format('aws s3 cp testCpcPlusValidationFile.json s3://{0}/testingCpcPlusValidationFile.json', secrets.DEV_S3_BUCKET) }}

      - name: Clean up
        run: |
          rm -vrf testingCpcPlusValidationFile.json
          rm -vrf ${{ secrets.PARTICIPATION_FILE_NAME }}